# Generated by Django 4.1.4 on 2023-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.CharField(choices=[('event1', 'event1'), ('event2', 'event2'), ('event3', 'event3')], default='event', max_length=255),
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
    ]
